# correcciones_ilegales.ini
# Sustancias ilegales — se les añade el prefijo [!] igual que MrKraken.
# Formato: clave=nombre_es  (mantenimiento manual)
# Fuente: global.back de MrKraken

items_commodities_GaspingWeevilEggs=<EM3>[!]</EM3> Gasping Weevil Eggs
items_commodities_altruciatoxin=<EM3>[!]</EM3> Altruciatoxin
items_commodities_altruciatoxin_unprocessed=<EM3>[!]</EM3> Revenant Tree Pollen
items_commodities_etam=<EM3>[!]</EM3> E'tam
items_commodities_maze=<EM3>[!]</EM3> Maze
items_commodities_neon=<EM3>[!]</EM3> Neon
items_commodities_slam=<EM3>[!]</EM3> SLAM
items_commodities_widow=<EM3>[!]</EM3> WiDoW
