name: Create Release

on:
  push:
    paths:
      - 'Data/Localization/spanish_(spain)/global.ini'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get date
        id: meta
        run: |
          DATE=$(TZ='Europe/Madrid' date +'%d/%m/%Y %H:%M')
          TAG=$(TZ='Europe/Madrid' date +'%Y%m%d%H%M%S')
          echo "tag=v${TAG}" >> $GITHUB_OUTPUT
          echo "name=Traduccion SC ${DATE}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.name }}
          files: Data/Localization/spanish_(spain)/global.ini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
